source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem "sqlite3", "~> 1.4.0"
gem 'pry'
gem 'rake'
gem 'activerecord', "~>6.1.7"
gem 'sinatra-activerecord'
gem 'rest-client'
gem 'dotenv'